/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <Cocoa/Cocoa.h>


@class NSColor, NSImage, NSScrollView, NSTimer, TCStatusMessageCell, TCTabBarControl, TCTabDataSource, TCThumbnailDownloader, TCTweet, TCTweetClipView, TCTweetStorage;

@interface TCTweetView : NSTableView <NSTextInputClient>
{
    id tabView;
    id mainController;
    TCTabBarControl *tabController;
    id tabManager;
    id postField;
    TCTweetStorage *tweetStorage;
    TCTabDataSource *tabConfigurer;
    TCThumbnailDownloader *thumbnailDownloader;
    TCTweetClipView *tweetClipView;
    TCStatusMessageCell *messageCell;
    long long realSelectedRow;
    NSImage *gradWhiteImageSmall;
    NSImage *gradWhiteImageLarge;
    NSImage *gradBlackImageSmall;
    NSImage *gradBlackImageLarge;
    BOOL selectionChanging;
    BOOL reverseColoring;
    NSScrollView *tweetScrollView;
    NSTimer *scrollAnimationTimer;
    TCTweet *animationTargetRow;
    BOOL shouldCenterRow;
    NSImage *deleteIcon;
    NSImage *replyIcon;
    NSImage *dmIcon;
    NSImage *favIcon;
    NSImage *favIconOn;
    NSImage *deleteIconShadow;
    NSImage *replyIconShadow;
    NSImage *dmIconShadow;
    NSImage *favIconShadow;
    NSColor *deleteIconColor;
    NSColor *replyIconColor;
    NSColor *dmIconColor;
    NSColor *favIconColor;
    NSColor *favIconOnColor;
    NSColor *deleteIconShadowColor;
    NSColor *replyIconShadowColor;
    NSColor *dmIconShadowColor;
    NSColor *favIconShadowColor;
    unsigned long long selectionStart;
    unsigned long long selectionEnd;
    BOOL requestIsValid;
    BOOL beingDragged;
    struct CGPoint menuOpenPos;
    BOOL menuIsOnHighlight;
}

+ (id)getOptimalColor:(id)arg1 withContrastAgainst:(id)arg2;
+ (void)initialize;
@property(readonly, nonatomic) TCStatusMessageCell *messageCell; // @synthesize messageCell;
@property(readonly, nonatomic) BOOL beingDragged; // @synthesize beingDragged;
@property(retain, nonatomic) TCTweetClipView *tweetClipView; // @synthesize tweetClipView;
@property(nonatomic) long long realSelectedRow; // @synthesize realSelectedRow;
@property(readonly, nonatomic) BOOL selectionChanging; // @synthesize selectionChanging;
@property(readonly, nonatomic) id tabView; // @synthesize tabView;
- (BOOL)writeSelectionToPasteboard:(id)arg1 types:(id)arg2;
- (id)validRequestorForSendType:(id)arg1 returnType:(id)arg2;
- (void)updateCoreTextCacheSize;
- (BOOL)isTweetSelected:(id)arg1;
- (BOOL)areTweetsVisible:(id)arg1;
- (BOOL)validateMenuItem:(id)arg1;
- (id)menuForEvent:(id)arg1;
- (void)doCommandBySelector:(SEL)arg1;
- (void)setMarkedText:(id)arg1 selectedRange:(struct _NSRange)arg2 replacementRange:(struct _NSRange)arg3;
- (struct _NSRange)markedRange;
- (BOOL)hasMarkedText;
- (BOOL)drawsVerticallyForCharacterAtIndex:(unsigned long long)arg1;
- (void)insertText:(id)arg1 replacementRange:(struct _NSRange)arg2;
- (id)validAttributesForMarkedText;
- (void)unmarkText;
- (struct CGRect)firstRectForCharacterRange:(struct _NSRange)arg1 actualRange:(struct _NSRange *)arg2;
- (unsigned long long)characterIndexForPoint:(struct CGPoint)arg1;
- (id)attributedSubstringForProposedRange:(struct _NSRange)arg1 actualRange:(struct _NSRange *)arg2;
- (void)resetCursorRects;
- (void)mouseDown:(id)arg1;
- (void)setSelectionEnd:(unsigned long long)arg1;
- (BOOL)beginWaitForDragInRange:(struct _NSRange)arg1 string:(id)arg2 atPosition:(struct CGPoint)arg3;
- (id)dragImageForString:(id)arg1;
- (void)selectAll:(id)arg1;
- (void)resetSelection;
- (id)selectedString;
- (void)setSelection:(struct _NSRange)arg1;
- (struct _NSRange)selectedRange;
- (id)getContextMenuFromEvent:(id)arg1;
- (id)getCopyMenuForTweet:(id)arg1;
- (id)getFilterMenu;
- (void)noteHeightOfRowsWithIndexesChanged:(id)arg1;
- (void)addUserIDAndKeywordToFilter:(id)arg1;
- (void)addUserIDToFilter:(id)arg1;
- (long long)getSelectedTabIndex:(id)arg1;
- (void)openImagePreview:(id)arg1;
- (void)translateTweet:(id)arg1;
- (void)searchForHashtags:(id)arg1;
- (void)copyFromMenu:(id)arg1;
- (void)openReplyHome:(id)arg1;
- (void)deleteSelection:(id)arg1;
- (void)officialRetweetSelection:(id)arg1;
- (void)retweetSelection:(id)arg1;
- (void)addToFav:(id)arg1;
- (void)sendMessage:(id)arg1;
- (void)sendReplyToAll:(id)arg1;
- (void)sendReply:(id)arg1;
- (void)openLink:(id)arg1;
- (void)openReply:(id)arg1;
- (void)openUserWeb:(id)arg1;
- (void)openUserPage:(id)arg1;
- (void)openInBrowser:(id)arg1;
- (void)viewDidEndLiveResize;
- (void)highlightSelectionInClipRect:(struct CGRect)arg1;
- (void)drawBackgroundInClipRect:(struct CGRect)arg1;
- (id)rightButtonImageForTweet:(id)arg1 isShadow:(BOOL)arg2;
- (id)leftButtonImageForTweet:(id)arg1 isShadow:(BOOL)arg2;
- (void)maskImage:(id)arg1 color:(id)arg2;
- (void)offsetColoringBy:(unsigned long long)arg1;
- (void)moveSelectionToPrevious;
- (void)moveSelectionToNext;
- (void)moveSelectionToBottom;
- (void)moveSelectionToTop;
- (void)selectTabAtIndex:(unsigned long long)arg1;
- (void)moveToPreviousTab:(id)arg1;
- (void)moveToNextTab:(id)arg1;
- (void)copyFromContextualMenu;
- (void)copy:(id)arg1;
- (void)openURLAtMenu:(id)arg1;
- (void)openURLFromString:(id)arg1;
- (void)lookupInDictionary:(id)arg1;
- (void)searchInTwitter:(id)arg1;
- (void)searchInGoogle:(id)arg1;
- (void)readLater:(id)arg1;
- (id)actualTextFromURLStr:(id)arg1 includeAtSymbol:(BOOL)arg2 includeHash:(BOOL)arg3 isURL:(char *)arg4;
- (id)urlInSelectedTweetAtLocation:(struct CGPoint)arg1;
- (void)copyWithFormat:(long long)arg1;
- (void)swipeWithEvent:(id)arg1;
- (void)keyDown:(id)arg1;
- (double)realScrollPos;
- (BOOL)isScrolledToTheTop;
- (void)scrollToTopWithAnimation;
- (void)scrollRowToVisibleWithAnimation:(long long)arg1;
- (void)scrollToRowWithAnimation:(long long)arg1;
- (void)scrollToRowWithAnimation:(long long)arg1 shouldCenterRow:(BOOL)arg2;
- (void)scrollToRowWithAnimation:(long long)arg1 shouldCenterRow:(BOOL)arg2 forceScroll:(BOOL)arg3;
- (void)scrollAnimationStep:(id)arg1;
- (void)cancelScrollAnimation;
- (void)keyUp:(id)arg1;
- (void)resignActive:(id)arg1;
- (void)sendReplyOrMessage:(BOOL)arg1;
- (struct CGSize)intercellSpacing;
- (void)fixWidthResizing;
- (void)awakeFromNib;
- (void)resetPointerRects;
- (id)initWithCoder:(id)arg1;
- (id)renderGradient:(id)arg1 withAngle:(double)arg2 withHeight:(double)arg3;

@end

