/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */


@class NSCell, NSClipView, NSMutableDictionary, NSMutableSet, NSPredicate, NSSearchField, NSString, NSTabView, NSTabViewItem, NSTableColumn, TCBreadcrumbManager, TCBreadcrumbView, TCEffectOverlay, TCMainController, TCTabBarControl, TCTabManager, TCTweetStorage, TCTweetView, TCTwitterEngineManager;

@interface TCTweetDataSource : NSObject
{
    TCTweetView *tweetView;
    TCTabBarControl *tabController;
    NSTabView *mainTabView;
    TCMainController *mainController;
    NSSearchField *searchField;
    TCTweetStorage *tweetStorage;
    TCTabManager *tabManager;
    TCTwitterEngineManager *twitterMan;
    TCEffectOverlay *overlayView;
    TCBreadcrumbView *breadView;
    NSTableColumn *statusColumn;
    NSCell *statusCell;
    NSClipView *tweetViewClipping;
    NSTabViewItem *selectedTab;
    NSMutableSet *currentReplies;
    NSString *currentUserID;
    long long targetReply;
    NSPredicate *searchPred;
    NSPredicate *tempSearchPred;
    NSMutableDictionary *recentUserTweetFetch;
    NSMutableDictionary *rowHeights;
    TCBreadcrumbManager *breadManager;
}

@property(readonly, nonatomic) TCBreadcrumbManager *breadManager; // @synthesize breadManager;
@property(retain, nonatomic) TCBreadcrumbView *breadView; // @synthesize breadView;
@property(retain, nonatomic) NSClipView *tweetViewClipping; // @synthesize tweetViewClipping;
@property(retain, nonatomic) TCEffectOverlay *overlayView; // @synthesize overlayView;
@property(retain, nonatomic) TCTwitterEngineManager *twitterMan; // @synthesize twitterMan;
@property(retain, nonatomic) TCTabManager *tabManager; // @synthesize tabManager;
@property(retain, nonatomic) TCTweetStorage *tweetStorage; // @synthesize tweetStorage;
@property(retain, nonatomic) NSSearchField *searchField; // @synthesize searchField;
@property(retain, nonatomic) TCMainController *mainController; // @synthesize mainController;
@property(retain, nonatomic) NSTabView *mainTabView; // @synthesize mainTabView;
@property(retain, nonatomic) TCTabBarControl *tabController; // @synthesize tabController;
@property(retain, nonatomic) TCTweetView *tweetView; // @synthesize tweetView;
- (id)currentTweets;
- (void)selectTweet:(id)arg1 inTab:(id)arg2;
- (id)colorForRow:(long long)arg1;
- (void)doubleClick:(id)arg1;
- (id)selectedTweet;
- (void)setAuxiliaryFilter:(id)arg1;
- (BOOL)deactivateFilter;
- (void)selectOldestUnread;
- (BOOL)tryToSelectUnreadInTab:(id)arg1;
- (void)tableView:(id)arg1 didClickTableColumn:(id)arg2;
- (void)tableViewColumnDidResize:(id)arg1;
- (BOOL)tableView:(id)arg1 shouldTrackCell:(id)arg2 forTableColumn:(id)arg3 row:(long long)arg4;
- (void)clearSelectedTab;
- (void)tabView:(id)arg1 didSelectTabViewItem:(id)arg2;
- (void)tabView:(id)arg1 willSelectTabViewItem:(id)arg2;
- (void)performScrollAfterTweetMarkerSync;
- (void)performScrollAfterTweetMarkerSyncFromNotification:(id)arg1;
- (void)performScrollAfterTweetMarkerSyncForTab:(id)arg1;
- (void)saveCurrentTabMarker:(BOOL)arg1;
- (void)setTabMarkerToTweetID:(id)arg1 forTab:(id)arg2;
- (void)tableViewSelectionIsChanging:(id)arg1;
- (void)updateSelectionStatus:(BOOL)arg1;
- (void)updateSelectedTweetInfo:(id)arg1;
- (void)updateSelection;
- (id)tableView:(id)arg1 objectValueForTableColumn:(id)arg2 row:(long long)arg3;
- (BOOL)selectionShouldChangeInTableView:(id)arg1;
- (double)tableView:(id)arg1 heightOfRow:(long long)arg2;
- (unsigned long long)rowOfTweet:(id)arg1;
- (id)tweetAtRow:(long long)arg1;
- (long long)numberOfRowsInTableView:(id)arg1;
- (void)getUserTimeline:(id)arg1;
- (void)pushSingleUserViewFromIconClick;
- (void)pushSingleUserView:(id)arg1;
- (void)pushSingleUserViewFromMenu:(id)arg1;
- (void)pushSingleUserViewWithPop:(BOOL)arg1;
- (void)getUserTimeline:(id)arg1 withSelection:(id)arg2;
- (void)pushConversationView:(id)arg1;
- (void)pushConversationViewFromMenu:(id)arg1;
- (void)pushConversationViewWithPop:(BOOL)arg1;
- (void)popToState:(id)arg1;
- (BOOL)popView;
- (void)resetView:(id)arg1;
- (void)resetViewToState:(id)arg1;
- (void)enterViewWithDetail:(id)arg1 shouldZoomIn:(BOOL)arg2 shouldAnimate:(BOOL)arg3;
- (void)restoreViewState:(id)arg1;
- (id)recordViewStateWithSelectedTweet:(id)arg1;
- (void)removeUserTimelineLimit:(id)arg1;
- (BOOL)attemptUserTimelineFetch:(id)arg1;
- (void)setCustomPredicate:(id)arg1;
- (void)resetRowHeights:(id)arg1;
- (void)invalidateRowHeight:(id)arg1;
- (void)fetchCurrentHeightStorage;
- (void)awakeFromNib;
- (id)init;

@end

